name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: npm ci
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          GIT_COMMITTER_NAME: "Paul Tibbetts"
          GIT_COMMITTER_EMAIL: "paul.tibbetts@stickee.co.uk"
        run: npx semantic-release
